import { Suspense } from 'react';

import { auth } from '@/auth';
import { ThemeProvider } from '@/components/ThemeProvider';
import Header from '@/components/header';
import { Inter } from 'next/font/google';

import './globals.css';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const getSession = await auth();
  return (
    <html lang='en' suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          className={inter.className}
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header getSession={getSession} />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
